### ISSUE TITLE
The BundleEntry Class Has No Matching Interface 

### ISSUE THREAD

**Issue by machariamuguku** [smilecdr/FHIR.ts#8] opened 2021-11-01 14:13 UTC
There's no IBundleEntry interface

**Comment by omarhoblos** [comment] 2021-11-01 14:26
Yup, definitely missed by swagger. Looks like the dependencies for it (eg IBundleLink) are also missing). Thanks for pointing this out.

**Comment by omarhoblos** [comment] 2021-11-01 14:41
Looking into this further - this is by design. This is because we're reserving interfaces strictly for resources, it didn't make sense to apply it here. Will close this.

**Closed by omarhoblos** 2021-11-01 14:41 UTC
